# Generated by Django 4.1.4 on 2022-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.ManyToManyField(blank=True, default=2, related_name='artworks', to='artists.style'),
        ),
    ]
