# Generated by Django 4.1.4 on 2022-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artwork_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='year_of_death',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artists.style'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
